openapi: 3.0.0
info:
  title: parrot
  version: 1.0.0
servers:
  - url: 'http://localhost:8100'
    description: Local

paths:
  /api/ping:
    get:
      tags:
        - Health Check
      summary: Ping service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: pong
  /api/messages:
    get:
      tags:
        - Messages
      summary: Get Messages
      parameters:
        - in: query
          name: chordId
          schema:
            type: string
          description: Chord Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Messages
      summary: Create Message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Real Madrid Fans
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /api/messages/{id}:
    get:
      tags:
        - Messages
      summary: Get Message by Id
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Message Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
