openapi: 3.0.0
info:
  title: parrot
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: Local

paths:
  /api/ping:
    get:
      tags:
        - Health Check
      summary: Ping service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: pong
